apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: atlas-sonar
  namespace: atlas-udd
  labels:
    name: atlas-sonar
spec:
  replicas: 1
  template:
    metadata:
      name: atlas-sonar
      labels:
        app: atlas-sonar
    spec:
      containers:
        - image: poccrmacr.azurecr.io/atlas_udd/sonarqube:1.0
          name: atlas-sonar
          env:
            - name: SONARQUBE_JDBC_USERNAME
              value: poccrm@poccrmdbmysql
            - name: SONARQUBE_JDBC_PASSWORD
              valueFrom:
                 secretKeyRef:
                    name: atlas-bd-passwords
                    key: pwd-sonar
            - name: SONARQUBE_JDBC_URL
              value: jdbc:mysql://poccrmdbmysql.mysql.database.azure.com:3306/sonar?useSSL=true&requireSSL=false&useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance
          ports:
            - containerPort: 9000
              name: sonarport
      volumes:
        - name: sonar-home-data
          persistentVolumeClaim:
                 claimName: sonar-claim
      imagePullSecrets:
            - name: poccrmacrauth