kind: ServiceAccount
apiVersion: v1
metadata:
  name: atlas-udd-sa
  namespace: atlas-udd

kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: atlas-udd-sa 
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "delete"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: atlas-udd-sa
subjects:
- kind: ServiceAccount
  name: atlas-udd-sa
  namespace: atlas-udd
roleRef:
  kind: Role
  name: atlas-udd-sa
  apiGroup: rbac.authorization.k8s.io
