apiVersion: v1
kind: Service
metadata:
   name: atlas-jenkins
   namespace: atlas-udd
   labels:
      name: atlas-jenkins
spec:
   type: LoadBalancer
   ports:
      - port: 80
        targetPort: 8080
        name: http-port 
      - port: 50000
        targetPort: 50000
        name: jnlp-port
   selector:
      app: atlas-jenkins