apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: git-cnf-claim
   namespace: atlas-udd
spec:
   accessModes:
      - ReadWriteMany
   storageClassName: git-cnf-sc 
   resources:
      requests:
         storage: 3Gi 
