apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: atlas-gitlab
  namespace: atlas-udd
  labels:
    name: atlas-gitlab
spec:
  replicas: 1
  template:
    metadata:
      name: atlas-gitlab
      labels:
        app: atlas-gitlab
    spec:
      containers:
        - image: atlas_udd/gitlab:1.0
          name: atlas-gitlab
          env:
            - name: GITLAB_OMNIBUS_CONFIG
              value: |
                postgresql['enable'] = false
                gitlab_rails['db_username'] = "poccrm@poccrmdb"
                gitlab_rails['db_password'] = "poc@2019"
                gitlab_rails['db_host'] = "poccrmdb.postgres.database.azure.com"
                gitlab_rails['db_port'] = "5432"
                gitlab_rails['db_database'] = "postgres"
                gitlab_rails['db_adapter'] = 'postgresql'
                gitlab_rails['db_encoding'] = 'utf8'
                external_url 'http://atlas.gitlab'
          ports:
            - containerPort: 80
              name: gitlabport1
            - containerPort: 443
              name: gitlabport2
            - containerPort: 22
              name: gitlabport3            
          volumeMounts:
            - name: gitlab-config
              mountPath: /etc/gitlab
            - name: gitlab-logs
              mountPath: /var/log/gitlab
            - name: gitlab-data
              mountPath: /var/opt/gitlab
      volumes:
        - name: gitlab-config
          persistentVolumeClaim:
            claimName: gitlab-config-claim
        - name: gitlab-logs
          persistentVolumeClaim:
            claimName: gitlab-log-claim
        - name: gitlab-data
          persistentVolumeClaim:
            claimName: gitlab-data-claim
