apiVersion: v1
kind: PersistentVolume
metadata:
   name: gitlab-config-claim1
   namespace: atlas-udd
spec:
   accessModes:
      - ReadWriteMany
   storageClassName: manual 
   capacity:
      storage: 3Gi
   hostPath:
      path: /vlm/gitlab/v1      
