apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   name: atlas-nexus
   namespace: atlas-udd
   labels:
      name: atlas-nexus
spec:
   replicas: 1
   template:
      metadata:
         name: atlas-nexus
         labels:
            app: atlas-nexus
      spec:
         containers:
            - image: poccrmacr.azurecr.io/atlas_udd/nexus:1.2
              name: atlas-nexus
              ports:
                - containerPort: 8081
                - containerPort: 5000 
              volumeMounts:
                - mountPath: /sonatype-work
                  name: nexus-data-volume
         securityContext:
            fsGroup: 1000
         volumes:
            - name: nexus-data-volume
              persistentVolumeClaim:
                 claimName: udd-nexus-claim
         imagePullSecrets:
            - name: poccrmacrauth